name: Discussion Notifier

on:
  discussion:
    types: [created]

jobs:
  discussion:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: Get Info
          run: |
            sudo apt-get install jq -y &> /dev/null
            echo "DIS_TITLE=$(jq --raw-output .discussion.title ${GITHUB_EVENT_PATH})" >> ${GITHUB_ENV}
            echo "DIS_URL=$(jq --raw-output .discussion.html_url ${GITHUB_EVENT_PATH})" >>  ${GITHUB_ENV}

            task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  clone_script:
    - repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
  build_script:
    - source build/envsetup.sh
    - lunch aosp_mido-user
    - m aex -j$(nproc --all)
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/mido/*.zip

        - name: Notify in Telegram
          run: |
            TgNotify() {
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.TG_CHAT_ID }}" \
              -d parse_mode=Markdown \
              -d text="${1}" \
              -d disable_web_page_preview=true
            }
            
            TgNotify "
            #DISCUSSION
            *New Discussion Started at* [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Title:* \`${DIS_TITLE}\`
            *User:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *Discussion URL:* [Here](${DIS_URL})" &> /dev/null
